const books = [
  {
    title: "The Gates of Athens",
    author: null,
    authorName: "Conn Iggulden",
    image: "URL",
    published: new Date(2021, 2, 18),
    synopsis: "A Persian king stands at last on Greek soil. His Immortals have come to raze the cities of the west. The Athenians are hopelessly outnumbered. The gods are silent. All they have is the shield line. Xanthippus takes a breath. If they cannot stand, all Greece will fall.Ten years later, Athens has betrayed its favourite son. When the Persians return, when they cross the Hellespont to take revenge on the Greeks, will Xanthippus come home to save his people? Athens cannot stand alone a second time.In desperation, the city calls on men of Sparta to block the pass at Thermopylae. To give them time. To give them hope.Featuring two of the most famous battles of the Ancient World, The Gates of Athens is a bravura piece of storytelling about a people driven to preserve their freedom at any cost.",
    pages: 464,
    languages: ["English"],
    ISBN: 1405937351
  },
  {
    title: "Ravenspur",
    author: null,
    authorName: "Conn Iggulden",
    image: "URL",
    published: new Date(2017, 0, 12),
    synopsis: "King Edward of York has been driven out of England. Queen Elizabeth and her children tremble in sanctuary at Westminster Abbey. The House of Lancaster has won the crown, but York will not go quietly. Desperate to reclaim his throne, Edward lands at Ravenspur with a half-drowned army and his brother Richard at his side. Every hand is against them, every city gate is shut, yet the brothers York go on the attack.But neither sees that their true enemy is Henry Tudor, now grown into a man. As the Red Dragon - 'the man of destiny' - his claim to the throne leads to Bosworth Field and a battle that will call an end to the Wars of the Roses . . .",
    pages: 496,
    languages: ["English"],
    ISBN: 9781405921497
  },
  {
    title: "Dunstan",
    author: null,
    authorName: "Conn Iggulden",
    image: "URL",
    published: new Date(2018, 2, 8),
    synopsis: "Tenth century England: a divided and broken country of misrule. Yet King Athelstan, grandson of Alfred the Great, seeks to unite the kingdom under one crown. By his side is Dunstan of Glastonbury - priest, soldier, visionary and, some insist, traitor - whose task is to steward seven kings through fire, war, murder and fury to see Athelstan's dream come true. But what stain will it leave on his mortal soul?",
    pages: 480,
    languages: ["English"],
    ISBN: 140592151
  },
  {
    title: "Azincourt",
    author: null,
    authorName: "Bernard Cornwell",
    image: "URL",
    published: new Date(2009, 5,11),
    synopsis: "Azincourt, fought on October 25th 1415, St Crispin's Day, is one of England’s best-known battles, in part through the brilliant depiction of it in Shakespeare's Henry V, in part because it was a brilliant and unexpected English victory and in part because it was the first battle won by the use of the longbow - a weapon developed by the English which enabled them to dominate the European battlefields for the rest of the century. Bernard Cornwell’s Azincourt is a vivid, breathtaking and meticulously well-researched account of this momentous battle and its aftermath. From the varying viewpoints of nobles, peasants, archers, and horsemen, Azincourt skilfully brings to life the hours of relentless fighting, the desperation of an army crippled by disease and the exceptional bravery of the English soldiers?",
    pages: 512,
    languages: ["English"],
    ISBN: 7271220
  },
  {
    title: "1356",
    author: null,
    authorName: "Bernard Cornwell",
    image: "URL",
    published: new Date(2013, 5, 6),
    synopsis: "1356: France stands alert to danger. The English army, victorious at the battle of Crécy and led by the Black Prince, is invading and the French are hunting them down. The bloodiest battles of the Hundred Years War are yet to be fought. Thomas of Hookton, an English archer, becomes trapped with his outnumbered army. And here, near the town of Poitiers, an extraordinary confrontation will ignite one of the greatest battles of all time?",
    pages: 448,
    languages: ["English"],
    ISBN: 733186
  },
  {
    title: "Eagles in the Storm",
    author: null,
    authorName: "Ben Kane",
    image: "URL",
    published: new Date(2017, 2, 23),
    synopsis: "AD 15. The German chieftain Arminius has been defeated, one of the lost Roman eagles recovered, and thousands of German tribesmen slain. Yet these successes aren’t nearly enough for senior centurion Lucius Tullus. Not until Arminius is dead, his old legion’s eagle found and the enemy tribes completely vanquished will he rest. But Arminius – devious, fearless – is burning for revenge of his own. Charismatic as ever, he raises another large tribal army, which will harry the Romans the length and breadth of the land. Soon Tullus finds himself in a cauldron of bloodshed, treachery and danger. His mission to retrieve his legion’s eagle will be his most perilous yet…",
    pages: 345,
    languages: ["English"],
    ISBN: 9958073,
  },
  {
    title: "The Forgotten Legion",
    author: null,
    authorName: "Ben Kane",
    image: "URL",
    published: new Date(2011, 0, 6),
    synopsis: "Romulus and Fabiola are twins, born into slavery after their mother is raped by a drunken nobleman. At thirteen years old they are sold - Romulus to gladiator school, Fabiola into prostitution, where she will catch the eye of one of the most powerful men in Rome. Tarquinius is an Etruscan, a warrior and soothsayer, born enemy of Rome, but doomed to fight for the Republic in the Forgotten Legion. Brennus is a Gaul, his entire family killed by the Romans, and he rises to become one of the most famous and feared gladiators of his day. The lives of these characters are bound and interwoven in an odyssey which begins in a Rome riven by political corruption and violence, but ends far away, at the very border of the known world, where the tattered remnants of a once-huge Roman army - the Forgotten Legion - will fight against overwhelming odds, and the three men will meet their destiny.",
    pages: 672,
    languages: ["English"],
    ISBN: 995566286,
  },
  {
    title: "The Road to Rome",
    author: null,
    authorName: "Ben Kane",
    image: "URL",
    published: new Date(2011, 0, 20),
    synopsis: "Romulus and Fabiola are twins, born into slavery after their mother is raped by a drunken nobleman. At thirteen years old they are sold - Romulus to gladiator school, Fabiola into prostitution, where she will catch the eye of one of the most powerful men in Rome. Tarquinius is an Etruscan, a warrior and soothsayer, born enemy of Rome, but doomed to fight for the Republic in the Forgotten Legion. Brennus is a Gaul, his entire family killed by the Romans, and he rises to become one of the most famous and feared gladiators of his day. The lives of these characters are bound and interwoven in an odyssey which begins in a Rome riven by political corruption and violence, but ends far away, at the very border of the known world, where the tattered remnants of a once-huge Roman army - the Forgotten Legion - will fight against overwhelming odds, and the three men will meet their destiny.",
    pages: 672,
    languages: ["English"],
    ISBN: 9781848090163,
  },
];

export default books;